spring:
  application:
    name: app
  datasource:
    url: jdbc:mysql://localhost:3306/vote_guard?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true